// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJA020SC9ngXPOkdulsb7aWhwC7P_20o8',
    appId: '1:541893065707:web:fd290475afd7cdf5b537ae',
    messagingSenderId: '541893065707',
    projectId: 'vandadnotes-d0eed',
    authDomain: 'vandadnotes-d0eed.firebaseapp.com',
    storageBucket: 'vandadnotes-d0eed.appspot.com',
    measurementId: 'G-T2L4GCFVN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBquDoYYPgxChbjOAAD9EYrYkLSO97DotY',
    appId: '1:541893065707:android:b62291a2119e7e03b537ae',
    messagingSenderId: '541893065707',
    projectId: 'vandadnotes-d0eed',
    storageBucket: 'vandadnotes-d0eed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkr4Qzz9RskvHele8DsajijmEvRrKgXAQ',
    appId: '1:541893065707:ios:7f0662697ca39fe5b537ae',
    messagingSenderId: '541893065707',
    projectId: 'vandadnotes-d0eed',
    storageBucket: 'vandadnotes-d0eed.appspot.com',
    iosBundleId: 'iamnife.flutter.vandadNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkr4Qzz9RskvHele8DsajijmEvRrKgXAQ',
    appId: '1:541893065707:ios:cd2d633d7a92d276b537ae',
    messagingSenderId: '541893065707',
    projectId: 'vandadnotes-d0eed',
    storageBucket: 'vandadnotes-d0eed.appspot.com',
    iosBundleId: 'iamnife.flutter.vandadNotes.RunnerTests',
  );
}
